<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Framework.DI.Autofac</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Framework.CQRS\Framework.CQRS.csproj" />
      <ProjectReference Include="..\Framework.Database.MongoDB\Framework.Database.MongoDB.csproj" />
      <ProjectReference Include="..\Framework.Domain.Events\Framework.Domain.Events.csproj" />
      <ProjectReference Include="..\Framework.Domain.Repository\Framework.Domain.Repository.csproj" />
      <ProjectReference Include="..\Framework.EventManager.MongoDb\Framework.EventManager.MongoDb.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    </ItemGroup>

</Project>
